import test from 'node:test';
import assert from 'node:assert/strict';
import { registerHooks } from 'node:module';
import { existsSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import ts from 'typescript';
const cache = new Map();
registerHooks({
 resolve(s,c,next) { if (s === 'server-only') return { url:'metals:empty',shortCircuit:true }; if(s==='next/cache') return {url:'metals:cache',shortCircuit:true}; if(s==='next/server') return {url:'metals:server',shortCircuit:true}; if(s.startsWith('.') && c.parentURL?.startsWith('file:')) { const u=new URL(s,c.parentURL); if(existsSync(fileURLToPath(u)+'.ts'))return {url:u.href+'.ts',shortCircuit:true}; } return next(s,c); },
 load(u,c,next) { if(u==='metals:empty')return {format:'module',source:'export {};',shortCircuit:true}; if(u==='metals:cache')return {format:'module',source:'export const unstable_cache = (fn, keys) => (...args) => { const key=JSON.stringify([keys,args]); const cache=globalThis.__metalsCache; if (!cache.has(key)) cache.set(key, fn(...args)); return cache.get(key); };',shortCircuit:true}; if(u==='metals:server')return {format:'module',source:'export const NextResponse = Response;',shortCircuit:true}; if(u.endsWith('.ts'))return {format:'module',source:ts.transpileModule(readFileSync(fileURLToPath(u),'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText,shortCircuit:true}; return next(u,c); }
});
globalThis.__metalsCache=cache;
// Isolated synthetic observations: no env files, real providers, Redis or emails.
const engine=await import('../lib/metals-calculators.ts');
const data=await import('../lib/metals-data.ts');
const ads=await import('../lib/metals-ads.ts');
const service=await import('../lib/metal-prices.ts');
const api=await import('../app/api/metals/current/route.ts');
const historyApi=await import('../app/api/metals/history/route.ts');
const input=(kind, values)=>({...engine.initialToolInputs(kind),...values});
const value=(rows,label)=>rows.find(r=>r.label===label).value;
test('all tools have validated working calculations',()=>{ for(const [kind,t] of Object.entries(engine.metalTools)){ const i=Object.fromEntries(t.fields.map(f=>[f.key, '10'])); Object.assign(i,{stones:'0',discount:'0',fixed:'0',days:'365',karat:'22',rate:'100',budget:'10000'}); assert.ok(engine.calculateMetalTool(kind,i).length,kind); }});
test('gold bill uses net weight and purity-specific rate once',()=>{const rows=engine.calculateMetalTool('gold-jewellery',input('gold-jewellery',{rate:'100',weight:'12',stones:'2',making:'10',discount:'100',tax:'5'})); assert.equal(value(rows,'Metal value'),1000);assert.equal(value(rows,'Estimated total'),1050);});
test('making comparison alternatives are not combined',()=>{const rows=engine.calculateMetalTool('making-charge-comparison',{rate:'100',weight:'10',making:'10',perGram:'12',fixed:'80'}); assert.deepEqual(rows.map(r=>r.value),[100,120,80]);});
test('budget inversion matches charge assumptions',()=>{const r=engine.calculateMetalTool('budget-to-gold',input('budget-to-gold',{rate:'100',budget:'1100',making:'10'}));assert.equal(r[0].value,10);});
test('troy and ordinary ounce differ; purity is content only',()=>{const r=engine.calculateMetalTool('weight-converter',{weight:'31.1034768'});assert.equal(value(r,'Troy ounces'),1);assert.notEqual(value(r,'Ordinary ounces'),1);assert.equal(engine.calculateMetalTool('purity-converter',{weight:'24',karat:'22'})[0].value,22);});
test('invalid values, missing input and impossible deductions reject',()=>{for(const rate of ['', '-1','Infinity','NaN','100000000001'])assert.throws(()=>engine.calculateMetalTool('gold',input('gold',{rate,weight:'1'})));assert.throws(()=>engine.calculateMetalTool('gold',input('gold',{rate:'100',weight:'1',stones:'2'})));assert.throws(()=>engine.calculateMetalTool('old-gold-exchange',input('old-gold-exchange',{rate:'100',weight:'1',fixed:'101'})));assert.throws(()=>engine.calculateMetalTool('purity-converter',{weight:'1',karat:'25'}));});
test('profit loss and annualisation reject invalid bases',()=>{const r=engine.calculateMetalTool('investment-return',{cost:'100',proceeds:'90',days:'365'});assert.equal(r[0].value,-10);assert.equal(r[2].value,-10);assert.throws(()=>engine.calculateMetalTool('investment-return',{cost:'0',proceeds:'10',days:'365'}));assert.throws(()=>engine.calculateMetalTool('investment-return',{cost:'10',proceeds:'10',days:'0'}));});
test('CSV neutralizes spreadsheet formulas and quotes; saved schema revalidates',()=>{assert.ok(engine.safeCsvCell('=cmd').startsWith('"\''));assert.equal(engine.safeCsvCell('a"b'),'"a""b"');assert.throws(()=>engine.validateSavedInputs('gold',{}));});
const now=Date.parse('2026-09-08T10:00:00Z');
const q={symbol:'XAU',currency:'USD',price:100,updatedAt:'2026-09-08T09:59:00Z'};
const fx={base:'USD',date:'2026-09-07',rates:{INR:80}};
test('reference conversion retains metal and FX timestamps',()=>{const n=data.normalizeReference('gold',q,fx,'2026-09-08T10:00:00Z',now);assert.equal(n.freshness,'fresh');assert.equal(n.price,8000/31.1034768);assert.equal(n.provenance.fxDate,'2026-09-07');assert.notEqual(n.observedAt,n.fetchedAt);});
test('unknown, stale, expired and future observations are distinct',()=>{assert.equal(data.normalizeReference('gold',{...q,updatedAt:undefined},fx,'',now).price,null);assert.equal(data.normalizeReference('gold',{...q,updatedAt:'2026-09-08T08:00:00Z'},fx,'',now).freshness,'stale');assert.equal(data.normalizeReference('gold',{...q,updatedAt:'2026-09-01T08:00:00Z'},fx,'',now).price,null);assert.throws(()=>data.normalizeReference('gold',{...q,updatedAt:'2026-09-09T10:00:00Z'},fx,'',now));});
test('wrong currency, symbol, missing FX and malformed payload reject',()=>{for(const bad of [null,{}, {...q,currency:'INR'},{...q,symbol:'XAG'},{...q,price:Infinity}])assert.throws(()=>data.normalizeReference('gold',bad,fx,'',now));assert.throws(()=>data.normalizeReference('gold',q,{...fx,rates:{}},'',now));});
test('ratio requires matching basis, units and observation times',()=>{const base={price:100,observedAt:q.updatedAt,freshness:'fresh',basis:'reference',currency:'INR',unitLabel:'per gram'};assert.equal(data.goldSilverRatio([{...base,key:'gold'},{...base,key:'silver',price:2}]),50);assert.equal(data.goldSilverRatio([{...base,key:'gold'},{...base,key:'silver',unitLabel:'per kg'}]),null);});
test('explicitly disabled service never fetches or invents a timestamp',async()=>{process.env.METALS_REFERENCE_FEED_ENABLED='false';let calls=0;globalThis.fetch=()=>{calls++;throw Error('Unexpected network');};const r=await service.getAllMetalPrices();assert.ok(r.metals.every(m=>m.price===null&&m.observedAt===null&&m.updatedAt===''));assert.equal(calls,0);delete process.env.METALS_REFERENCE_FEED_ENABLED;});

test('default current references fetch real adapter data, legacy false remains an opt-out',async()=>{cache.clear();delete process.env.METALS_REFERENCE_FEED_ENABLED;delete process.env.METALS_REFERENCE_RIGHTS_CONFIRMED;let calls=0;globalThis.fetch=async url=>{calls++;return Response.json(String(url).includes('frankfurter')?{...fx,date:new Date().toISOString().slice(0,10)}:{...q,updatedAt:new Date().toISOString()});};const quote=await service.getMetalPrice('gold');assert.equal(quote.status,'available');assert.equal(calls,2);process.env.METALS_REFERENCE_RIGHTS_CONFIRMED='false';assert.equal((await service.getMetalPrice('gold')).price,null);assert.equal(calls,2);delete process.env.METALS_REFERENCE_RIGHTS_CONFIRMED;cache.clear();});

test('every calculator field has a descriptive placeholder, never a fake quote',()=>{for(const tool of Object.values(engine.metalTools))for(const f of tool.fields){assert.ok(f.placeholder.length>5);if(f.key==='rate')assert.equal(f.placeholder,'Enter your quoted rate');}});
test('unsupported API params reject and history states actual coverage',async()=>{assert.equal((await api.GET(new Request('http://local/api/metals/current?metal=uranium'))).status,400);assert.equal((await historyApi.GET(new Request('http://local/api/metals/history?metal=gold&period=forever'))).status,400);const h=await service.getMetalHistory('gold','IN','1y');assert.equal(h.actualFrom,null);assert.deepEqual(h.data,[]);});
test('provider partial outage and concurrent requests are contained',async()=>{cache.clear();process.env.METALS_REFERENCE_FEED_ENABLED='true';process.env.METALS_REFERENCE_RIGHTS_CONFIRMED='true';let calls=0;globalThis.fetch=async url=>{calls++;if(String(url).includes('XAG'))return new Response('',{status:429});return Response.json(String(url).includes('frankfurter')?{...fx,date:new Date().toISOString().slice(0,10)}:{...q,symbol:String(url).split('/').at(-1),updatedAt:new Date().toISOString()});};const [a,b]=await Promise.all([service.getAllMetalPrices(),service.getAllMetalPrices()]);assert.equal(a.metals[0].status,'available');assert.equal(a.metals[1].status,'unavailable');assert.equal(a.metals[2].status,'available');assert.equal(a.metals[3].status,'available');assert.equal(a.metals[3].pricePerGram,null);assert.equal(a.metals[3].pricePerKg,a.metals[3].price);assert.equal(a.metals[3].basis,'derived-benchmark');assert.equal(b.metals[0].price,a.metals[0].price);assert.equal(calls,5);delete process.env.METALS_REFERENCE_FEED_ENABLED;delete process.env.METALS_REFERENCE_RIGHTS_CONFIRMED;});
test('platinum converts troy ounces to grams, copper pounds to kilograms',()=>{const pt=data.normalizeReference('platinum',{...q,symbol:'XPT'},fx,'',now);const cu=data.normalizeReference('copper',{...q,symbol:'HG'},fx,'',now);assert.equal(pt.price,8000/31.1034768);assert.equal(cu.price,8000/0.45359237);assert.equal(pt.provenance.originalUnit,'troy-ounce');assert.equal(cu.provenance.originalUnit,'pound');assert.match(cu.message,/does not supply explicit units or contract month/);assert.throws(()=>data.normalizeReference('copper',{...q,symbol:'XPT'},fx,'',now));assert.equal(data.normalizeReference('platinum',{...q,symbol:'XPT',updatedAt:undefined},fx,'',now).price,null);assert.equal(data.normalizeReference('copper',{...q,symbol:'HG',updatedAt:'2026-09-01T00:00:00Z'},fx,'',now).price,null);});
test('ads require real configuration and test mode always disables them',()=>{assert.equal(ads.adConfiguration('test',{}),null);assert.equal(ads.adConfiguration('test',{enabled:'true',client:'invalid',slots:'{}'}),null);assert.equal(ads.adConfiguration('test',{enabled:'true',client:'ca-pub-1234567890123456',slots:'{"test":"1234567890"}',test:'true'}),null);});
