"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { ArrowRight, Check, ChevronRight, CircleHelp, FileText, ShieldCheck, X } from "lucide-react";
import AdSlot from "./AdSlot";
import { AssetActionButtons } from "./WatchlistAlertsClient";
import { bondCategories, bondQuestions, bonds, bondSources, type Bond, type BondCategory, type BondType } from "../../lib/bonds";

type BondsView = "dashboard" | "explore" | "compare" | "providers" | "category" | "detail" | "calculator";

const disclaimer = "Educational information only. Bond investing involves market, credit, liquidity, reinvestment and tax risks. Yields, ratings and availability change. Read the official offer document and current terms before investing.";

export default function BondsModule({ view = "dashboard", category, bond }: { view?: BondsView; category?: BondCategory; bond?: Bond }) {
  if (view === "category" && category) return <BondCategoryPage category={category} />;
  if (view === "detail" && bond) return <BondDetailPage bond={bond} />;
  if (view === "explore") return <ExplorePage />;
  if (view === "compare") return <ComparePage />;
  if (view === "providers") return <ProvidersPage />;
  if (view === "calculator") return <BondCalculator />;
  return <BondsDashboard />;
}

function BondsDashboard() {
  const [query, setQuery] = useState("");
  const filtered = bondCategories.filter((item) => `${item.name} ${item.summary} ${item.audience}`.toLowerCase().includes(query.toLowerCase().trim()));
  return <div className="bonds-module">
    <section className="bonds-command glass-panel"><div><span className="finance-eyebrow">Fixed-income intelligence</span><h2>Understand, compare and explore bonds in India.</h2><p>Compare yield, maturity, coupon, ratings and risks across government and corporate bonds.</p></div><div className="bonds-command-actions"><input aria-label="Search bonds" placeholder="Search issuer, maturity, rating..." value={query} onChange={(event) => setQuery(event.target.value)} /><Link className="primary-button" href="/bonds/compare">Compare bonds <ArrowRight size={16} /></Link></div></section>
    <AdSlot id="bonds-dashboard-top" label="Bond advertisement" />
    <section className="glass-panel bonds-data-status"><span className="finance-eyebrow">Live data status</span><h2>Bond yields are not shown without a verified market feed.</h2><p>Government auctions, secondary-market prices, coupons, ratings and liquidity must be refreshed from RBI, NSE, BSE or an approved bond-data provider. The catalogue below is educational and not a live quote feed.</p><a className="outline-button" href="https://www.rbi.org.in/" target="_blank" rel="noreferrer">Open RBI source <ArrowRight size={16} /></a></section>
    <section><div className="bonds-section-heading"><div><span className="finance-eyebrow">Explore fixed income</span><h2>Bond categories</h2></div><Link href="/bonds/explore">Open screener <ChevronRight size={16} /></Link></div><div className="bonds-category-grid">{filtered.map((item) => <CategoryCard category={item} key={item.key} />)}</div></section>
    <div className="bonds-dashboard-grid"><section className="glass-panel bonds-question-panel"><div className="bonds-section-heading"><div><span className="finance-eyebrow">Popular questions</span><h2>What investors research most</h2></div></div><div className="bonds-question-list">{bondQuestions.slice(0, 6).map((question) => <Link href="/bonds/explore" key={question}><CircleHelp size={16} />{question}<ChevronRight size={16} /></Link>)}</div></section><section className="glass-panel bonds-check-panel"><div className="bonds-section-heading"><div><span className="finance-eyebrow">Decision guide</span><h2>Before buying a bond</h2></div></div><div className="bonds-check-list"><p><Check size={17} />Compare coupon with yield to maturity</p><p><Check size={17} />Check issuer, rating and security status</p><p><Check size={17} />Review maturity and interest-rate sensitivity</p><p><Check size={17} />Understand liquidity and exit options</p><p><Check size={17} />Read tax treatment and offer documents</p></div><Link className="outline-button" href="/bonds/calculators">Open bond calculators</Link></section></div>
    <AdSlot id="bonds-dashboard-mid" label="Sponsored bond placement" />
    <section><div className="bonds-section-heading"><div><span className="finance-eyebrow">Bond directory</span><h2>Reference bonds by segment</h2></div><Link href="/bonds/explore">View all <ChevronRight size={16} /></Link></div><div className="bonds-card-grid">{bonds.slice(0, 6).map((bond) => <BondCard bond={bond} key={bond.slug} />)}</div></section><SourceNote />
  </div>;
}

function CategoryCard({ category }: { category: BondCategory }) { return <Link className="bonds-category-card glass-panel" href={category.route} style={{ "--bond-color": category.color } as React.CSSProperties}><span className="bonds-category-icon"><FileText size={20} /></span><h3>{category.name}</h3><p>{category.summary}</p><small>{category.audience}</small><span className="bonds-card-link">Learn more <ChevronRight size={15} /></span></Link>; }

function BondCard({ bond }: { bond: Bond }) { return <article className="glass-panel bonds-card" data-bond-type={bond.type}><div className="bonds-card-head"><span className="bonds-card-mark">{bond.issuer.slice(0, 2).toUpperCase()}</span><div><h3>{bond.name}</h3><small>{bond.issuer} · {bond.source}</small></div></div><p>{bond.summary}</p><div className="bonds-chip-row"><span>{bond.type}</span><span>{bond.rating}</span><span>{bond.maturity}</span></div><div className="bonds-metrics"><div><small>YTM</small><b>{bond.ytm}</b></div><div><small>Coupon</small><b>{bond.coupon}</b></div><div><small>Minimum</small><b>{bond.minimum}</b></div></div><div className="bonds-card-footer"><Link className="bonds-profile-button" href={`/bonds/${bond.slug}`}>View bond <ChevronRight size={15} /></Link><span>{bond.frequency}</span></div><AssetActionButtons compact asset={{ assetKey: `bond:${bond.slug}`, symbol: bond.slug, name: bond.name, assetType: "bond", route: `/bonds/${bond.slug}`, market: bond.issuer }} /></article>; }

function ExplorePage() {
  const [type, setType] = useState<"all" | BondType>("all"); const [query, setQuery] = useState("");
  const filtered = useMemo(() => bonds.filter((bond) => (type === "all" || bond.type === type) && `${bond.name} ${bond.issuer} ${bond.rating}`.toLowerCase().includes(query.toLowerCase().trim())), [query, type]);
  return <div className="bonds-module"><section className="bonds-command glass-panel"><div><span className="finance-eyebrow">Bond screener</span><h2>Find bonds by yield, issuer and maturity.</h2><p>Reference profiles for education. Verify live prices, yields and documents before transacting.</p></div><Link className="outline-button" href="/bonds/compare">Compare bonds</Link></section><AdSlot id="bonds-explore-top" label="Bond advertisement" /><section className="glass-panel bonds-explorer"><div className="bonds-filter-row"><input aria-label="Search bond profiles" placeholder="Search issuer or bond..." value={query} onChange={(event) => setQuery(event.target.value)} /><div className="bonds-tabs">{[["all", "All"], ["government", "Government"], ["treasury", "T-bills"], ["corporate", "Corporate"], ["green", "Green"]].map(([value, label]) => <button className={type === value ? "active" : ""} key={value} onClick={() => setType(value as "all" | BondType)} type="button">{label}</button>)}</div></div><div className="bonds-card-grid">{filtered.map((bond) => <BondCard bond={bond} key={bond.slug} />)}</div>{filtered.length === 0 ? <p className="bonds-empty">No bond profiles match those filters.</p> : null}</section><SourceNote /></div>;
}

function BondCategoryPage({ category }: { category: BondCategory }) { return <div className="bonds-module"><div className="bonds-breadcrumb"><Link href="/bonds">Bonds</Link><ChevronRight size={14} />{category.name}</div><section className="bonds-detail-hero glass-panel" style={{ "--bond-color": category.color } as React.CSSProperties}><span className="bonds-category-icon"><FileText size={23} /></span><div><span className="finance-eyebrow">{category.name}</span><h2>{category.name} in India</h2><p>{category.summary}</p><small>Useful for: {category.audience}</small></div><Link className="primary-button" href="/bonds/explore">Explore bonds <ArrowRight size={16} /></Link></section><AdSlot id={`${category.key}-bonds-top`} label="Bond advertisement" /><div className="bonds-benefit-columns"><BenefitPanel title="Potential benefits" items={category.benefits} positive /><BenefitPanel title="Limitations and disadvantages" items={category.disadvantages} /></div><section className="glass-panel bonds-content-panel"><span className="finance-eyebrow">Reference profiles</span><h2>{category.name} examples</h2><div className="bonds-card-grid">{bonds.filter((bond) => bond.type === category.key).map((bond) => <BondCard bond={bond} key={bond.slug} />)}</div></section><SourceNote /></div>; }

function BondDetailPage({ bond }: { bond: Bond }) { return <div className="bonds-module"><div className="bonds-breadcrumb"><Link href="/bonds/explore">Bond screener</Link><ChevronRight size={14} />{bond.name}</div><section className="bonds-detail-hero glass-panel"><span className="bonds-card-mark large">{bond.issuer.slice(0, 2).toUpperCase()}</span><div><span className="finance-eyebrow">Bond profile · {bond.type}</span><h2>{bond.name}</h2><p>{bond.summary}</p><small>Issuer: {bond.issuer} · Source: {bond.source}</small></div><Link className="outline-button" href="/bonds/compare">Compare <ArrowRight size={16} /></Link></section><div className="bonds-detail-grid"><section className="glass-panel bonds-content-panel"><span className="finance-eyebrow">Bond terms</span><h2>Key reference data</h2><div className="bonds-detail-metrics">{[["Yield to maturity", bond.ytm], ["Coupon", bond.coupon], ["Maturity", bond.maturity], ["Rating", bond.rating], ["Minimum investment", bond.minimum], ["Payout frequency", bond.frequency]].map(([label, value]) => <div key={label}><small>{label}</small><b>{value}</b></div>)}</div></section><section className="glass-panel bonds-content-panel"><span className="finance-eyebrow">Risk check</span><h2>What to review</h2><div className="bonds-risk-list"><p><ShieldCheck size={17} />{bond.risk}</p><p><X size={17} />Rating does not guarantee repayment or liquidity.</p><p><X size={17} />Selling before maturity can result in a gain or loss.</p></div></section></div><AdSlot id={`bond-${bond.slug}-mid`} label="Sponsored bond placement" /><SourceNote /></div>; }

function ComparePage() { const [left, setLeft] = useState(bonds[0].slug); const [right, setRight] = useState(bonds[2].slug); const first = bonds.find((bond) => bond.slug === left)!; const second = bonds.find((bond) => bond.slug === right)!; const rows = [["Issuer", first.issuer, second.issuer], ["Type", first.type, second.type], ["Coupon", first.coupon, second.coupon], ["YTM", first.ytm, second.ytm], ["Maturity", first.maturity, second.maturity], ["Rating", first.rating, second.rating], ["Minimum", first.minimum, second.minimum], ["Risk focus", first.risk, second.risk]]; return <div className="bonds-module"><section className="bonds-command glass-panel"><div><span className="finance-eyebrow">Transparent comparison</span><h2>Compare bonds by income, time and risk.</h2><p>This educational comparison does not rank or recommend a security.</p></div><Link className="outline-button" href="/bonds/calculators">Use calculator</Link></section><AdSlot id="bonds-compare-top" label="Bond advertisement" /><section className="glass-panel bonds-comparison-panel"><div className="bonds-select-row"><label>Bond A<select value={left} onChange={(event) => setLeft(event.target.value)}>{bonds.map((bond) => <option key={bond.slug} value={bond.slug}>{bond.name}</option>)}</select></label><label>Bond B<select value={right} onChange={(event) => setRight(event.target.value)}>{bonds.map((bond) => <option key={bond.slug} value={bond.slug}>{bond.name}</option>)}</select></label></div><div className="bonds-table-wrap"><table className="bonds-table"><thead><tr><th>Feature</th><th>{first.name}</th><th>{second.name}</th></tr></thead><tbody>{rows.map((row) => <tr key={row[0]}><th>{row[0]}</th><td>{row[1]}</td><td>{row[2]}</td></tr>)}</tbody></table></div><p className="bonds-table-note">Actual market prices, yields, taxes, documents and liquidity can change. Use current official information for decisions.</p></section><SourceNote /></div>; }

function ProvidersPage() { const groups = [{ title: "Government access", items: ["RBI Retail Direct", "NSE and BSE debt markets", "Banks and primary dealers"] }, { title: "Corporate bond access", items: ["Registered brokers", "Bond marketplaces", "Issuer and lead-manager platforms"] }, { title: "Key issuers", items: ["Government of India", "State governments", "PSUs, banks and NBFCs"] }]; return <div className="bonds-module"><section className="bonds-command glass-panel"><div><span className="finance-eyebrow">Issuer and platform directory</span><h2>Where bonds come from and where investors access them.</h2><p>Directory categories help you verify issuer documents, platform disclosures, fees and eligibility. Presence is not a recommendation.</p></div><a className="outline-button" href="https://www.rbi.org.in/" target="_blank" rel="noreferrer">Open RBI <ArrowRight size={16} /></a></section><AdSlot id="bonds-providers-top" label="Bond advertisement" /><div className="bonds-provider-grid">{groups.map((group) => <section className="glass-panel bonds-provider-card" key={group.title}><span className="bonds-category-icon"><FileText size={19} /></span><h2>{group.title}</h2>{group.items.map((item) => <p key={item}><Check size={16} />{item}</p>)}<small>Verify current registration, fees, eligibility and official disclosures.</small></section>)}</div><SourceNote /></div>; }

function BondCalculator() { const [principal, setPrincipal] = useState(100000); const [coupon, setCoupon] = useState(7.5); const [years, setYears] = useState(5); const [tax, setTax] = useState(20); const annual = principal * coupon / 100; const total = annual * years + principal; const postTax = annual * (1 - tax / 100); return <div className="bonds-module"><section className="bonds-command glass-panel"><div><span className="finance-eyebrow">Bond planning tool</span><h2>Estimate coupon income and maturity value.</h2><p>Illustrative calculation only. It does not include market price changes, accrued interest, fees or every tax rule.</p></div></section><section className="glass-panel bonds-calculator"><div className="bonds-form"><label>Investment amount<input type="number" min="0" value={principal} onChange={(event) => setPrincipal(Number(event.target.value))} /></label><label>Coupon rate (%)<input type="number" min="0" step="0.01" value={coupon} onChange={(event) => setCoupon(Number(event.target.value))} /></label><label>Holding period (years)<input type="number" min="1" value={years} onChange={(event) => setYears(Number(event.target.value))} /></label><label>Illustrative tax rate (%)<input type="number" min="0" max="100" value={tax} onChange={(event) => setTax(Number(event.target.value))} /></label></div><aside className="bonds-calculator-result"><span>Estimated annual coupon</span><strong>₹{annual.toLocaleString("en-IN", { maximumFractionDigits: 0 })}</strong><div><small>Pre-tax maturity value</small><b>₹{total.toLocaleString("en-IN", { maximumFractionDigits: 0 })}</b></div><div><small>Illustrative annual post-tax coupon</small><b>₹{postTax.toLocaleString("en-IN", { maximumFractionDigits: 0 })}</b></div><em>Coupon compounding, price movement and tax treatment may differ from this simplified estimate.</em></aside></section><SourceNote /></div>; }

function BenefitPanel({ title, items, positive = false }: { title: string; items: string[]; positive?: boolean }) { return <section className={positive ? "glass-panel bonds-benefit-box positive" : "glass-panel bonds-benefit-box caution"}><h2>{title}</h2>{items.map((item) => <p key={item}>{positive ? <Check size={17} /> : <X size={17} />}{item}</p>)}</section>; }

function SourceNote() { return <section className="bonds-source-note"><strong>Sources and disclosure</strong><p>{disclaimer}</p><div>{bondSources.map((source) => <a href={source.href} key={source.href} target="_blank" rel="noreferrer">{source.label}</a>)}</div></section>; }
