"use client";

import Link from "next/link";
import { ArrowRight, ShieldCheck } from "lucide-react";
import AdSlot from "./AdSlot";
import { insuranceCategories, insuranceProviders } from "../../lib/insurance";

export default function InsuranceLandingModule() {
  return <div className="insurance-module"><section className="insurance-command glass-panel"><div><span className="finance-eyebrow">Insurance intelligence</span><h2>Understand cover, exclusions and claims in India.</h2><p>Insurance premiums and claim metrics are provider-specific. This page shows education and source-linked directories without inventing quotes.</p></div><Link className="primary-button" href="/insurance/compare">Compare policy factors <ArrowRight size={16} /></Link></section><AdSlot id="insurance-dashboard-top" label="Insurance advertisement" /><section><div className="insurance-section-heading"><div><span className="finance-eyebrow">Explore cover</span><h2>Insurance categories</h2></div></div><div className="insurance-category-grid">{insuranceCategories.map((category) => <Link className="insurance-category-card glass-panel" href={category.route} key={category.key}><span className="insurance-icon"><ShieldCheck size={20} /></span><h3>{category.name}</h3><p>{category.summary}</p><small>{category.audience}</small><span className="insurance-card-link">Learn more <ArrowRight size={15} /></span></Link>)}</div></section><section className="glass-panel insurance-content-panel"><div className="insurance-check-list"><p><ShieldCheck size={17} />Read the policy wording and Customer Information Sheet</p><p><ShieldCheck size={17} />Check exclusions, waiting periods, deductibles and renewal terms</p><p><ShieldCheck size={17} />Verify insurer registration and grievance channels</p></div><Link className="outline-button" href="/insurance/providers">Open provider directory <ArrowRight size={15} /></Link></section><section className="glass-panel insurance-content-panel"><span className="finance-eyebrow">Directory preview</span><h2>Official provider links</h2><div className="insurance-chip-row large">{insuranceProviders.slice(0, 8).map((provider) => <a href={provider.website} target="_blank" rel="noreferrer" key={provider.slug}>{provider.name}</a>)}</div></section></div>;
}
