export type CryptoType = "layer-1" | "layer-2" | "defi" | "stablecoin" | "meme" | "web3";
export type CryptoAsset = { slug: string; name: string; symbol: string; type: CryptoType; chain: string; priceInr: number; priceUsd: number; change24h: number; marketCap: string; volume: string; rank: number; circulatingSupply: string; maxSupply: string; ath: string; summary: string; risk: string; source: string };
export type CryptoCategory = { key: CryptoType; name: string; summary: string; audience: string; color: string; route: string; benefits: string[]; disadvantages: string[] };

export const cryptoAssets: CryptoAsset[] = [
  { slug: "bitcoin", name: "Bitcoin", symbol: "BTC", type: "layer-1", chain: "Bitcoin", priceInr: 5784200, priceUsd: 69210, change24h: 2.8, marketCap: "₹114.2T", volume: "₹2.8T", rank: 1, circulatingSupply: "19.7M BTC", maxSupply: "21M BTC", ath: "₹6,420,000", summary: "The largest crypto asset by market capitalisation, designed as a decentralised digital-money network.", risk: "Very high volatility, custody, regulatory and market risk", source: "Reference market-data snapshot" },
  { slug: "ethereum", name: "Ethereum", symbol: "ETH", type: "layer-1", chain: "Ethereum", priceInr: 312800, priceUsd: 3745, change24h: 1.9, marketCap: "₹37.6T", volume: "₹1.4T", rank: 2, circulatingSupply: "120.4M ETH", maxSupply: "No fixed maximum", ath: "₹403,000", summary: "A programmable blockchain supporting smart contracts, applications, tokens and layer-2 networks.", risk: "Network, smart-contract, staking and market risk", source: "Reference market-data snapshot" },
  { slug: "solana", name: "Solana", symbol: "SOL", type: "layer-1", chain: "Solana", priceInr: 14260, priceUsd: 171, change24h: -1.2, marketCap: "₹8.1T", volume: "₹520B", rank: 5, circulatingSupply: "475M SOL", maxSupply: "Inflationary", ath: "₹23,800", summary: "A high-throughput smart-contract network used by consumer, DeFi and trading applications.", risk: "Network reliability, concentration and market risk", source: "Reference market-data snapshot" },
  { slug: "tether", name: "Tether", symbol: "USDT", type: "stablecoin", chain: "Multi-chain", priceInr: 83.25, priceUsd: 1, change24h: 0.03, marketCap: "₹10.1T", volume: "₹4.5T", rank: 3, circulatingSupply: "120B USDT", maxSupply: "Issuer-controlled", ath: "₹94.20", summary: "A dollar-referenced stablecoin used for settlement, trading and liquidity across networks.", risk: "Depeg, issuer, reserve, regulatory and counterparty risk", source: "Reference market-data snapshot" },
  { slug: "polygon", name: "Polygon", symbol: "POL", type: "layer-2", chain: "Polygon", priceInr: 31.2, priceUsd: 0.37, change24h: 3.1, marketCap: "₹310B", volume: "₹18B", rank: 20, circulatingSupply: "9.9B POL", maxSupply: "Inflationary", ath: "₹244", summary: "A scaling and interoperability ecosystem connected to Ethereum applications.", risk: "Protocol, token migration and market risk", source: "Reference market-data snapshot" },
  { slug: "uniswap", name: "Uniswap", symbol: "UNI", type: "defi", chain: "Ethereum", priceInr: 920, priceUsd: 11.05, change24h: -0.8, marketCap: "₹550B", volume: "₹28B", rank: 18, circulatingSupply: "600M UNI", maxSupply: "1B UNI", ath: "₹4,150", summary: "A decentralised-exchange protocol token associated with automated liquidity markets.", risk: "Smart-contract, governance, liquidity and market risk", source: "Reference market-data snapshot" },
  { slug: "dogecoin", name: "Dogecoin", symbol: "DOGE", type: "meme", chain: "Dogecoin", priceInr: 18.7, priceUsd: 0.224, change24h: 5.4, marketCap: "₹2.7T", volume: "₹210B", rank: 8, circulatingSupply: "147B DOGE", maxSupply: "Inflationary", ath: "₹61.80", summary: "A high-profile meme-oriented crypto asset whose price is strongly sentiment-sensitive.", risk: "Extreme volatility, sentiment and unlimited-supply risk", source: "Reference market-data snapshot" },
  { slug: "chainlink", name: "Chainlink", symbol: "LINK", type: "web3", chain: "Multi-chain", priceInr: 1320, priceUsd: 15.85, change24h: 1.1, marketCap: "₹820B", volume: "₹40B", rank: 14, circulatingSupply: "587M LINK", maxSupply: "1B LINK", ath: "₹4,250", summary: "A decentralised-oracle network designed to connect smart contracts with external data.", risk: "Oracle adoption, token unlock and market risk", source: "Reference market-data snapshot" },
];

export const cryptoCategories: CryptoCategory[] = [
  { key: "layer-1", name: "Layer-1 networks", summary: "Base blockchains that process transactions and support applications directly.", audience: "Investors learning blockchain infrastructure", color: "#f59e0b", route: "/crypto/layer-1", benefits: ["Core network exposure", "Broad application ecosystems", "Network usage can be measured"], disadvantages: ["High volatility", "Competition between networks", "Technology and governance risk"] },
  { key: "layer-2", name: "Layer-2 networks", summary: "Scaling networks that extend or connect to a base blockchain.", audience: "Users interested in scaling and lower fees", color: "#60a5fa", route: "/crypto/layer-2", benefits: ["Scaling use cases", "Potentially lower transaction costs", "Growing application ecosystems"], disadvantages: ["Bridge and sequencer risk", "Complex token economics", "Dependence on base networks"] },
  { key: "defi", name: "DeFi protocols", summary: "Decentralised lending, exchange, liquidity and financial application tokens.", audience: "Advanced users researching on-chain finance", color: "#a78bfa", route: "/crypto/defi", benefits: ["Open financial protocols", "On-chain transparency", "Programmable liquidity"], disadvantages: ["Smart-contract exploits", "Impermanent loss", "Oracle and governance risk"] },
  { key: "stablecoin", name: "Stablecoins", summary: "Tokens designed to reference fiat currencies or other assets.", audience: "Settlement and liquidity users", color: "#34d399", route: "/crypto/stablecoins", benefits: ["Lower price movement than many crypto assets", "Useful for settlement", "Multi-chain availability"], disadvantages: ["Depeg risk", "Issuer and reserve risk", "Regulatory and counterparty risk"] },
  { key: "meme", name: "Meme coins", summary: "Community and sentiment-led tokens with unusually high volatility.", audience: "Users studying speculation and market psychology", color: "#fb7185", route: "/crypto/meme-coins", benefits: ["Strong community visibility", "High liquidity in popular assets", "Useful for sentiment research"], disadvantages: ["Extreme volatility", "Manipulation and concentration risk", "Weak fundamental utility may exist"] },
  { key: "web3", name: "Web3 infrastructure", summary: "Oracles, storage, identity, gaming and application infrastructure assets.", audience: "Technology and adoption researchers", color: "#22c55e", route: "/crypto/web3", benefits: ["Technology-focused use cases", "Cross-chain application exposure", "Developer activity can be tracked"], disadvantages: ["Adoption uncertainty", "Token unlocks", "Technical and execution risk"] },
];

export const cryptoExchanges = [
  { name: "India-accessible exchange", type: "Centralised exchange", features: "INR deposits, spot trading, KYC and wallet withdrawals", status: "Verify current FIU and service status", source: "Exchange disclosure" },
  { name: "RBI-linked payment route", type: "Payment rail", features: "INR banking and payment availability can vary", status: "Verify bank and platform terms", source: "Platform disclosure" },
  { name: "Self-custody wallet", type: "Wallet", features: "User-controlled keys and read-only portfolio tracking", status: "Never share a seed phrase", source: "Security education" },
  { name: "On-chain DEX", type: "Decentralised exchange", features: "Wallet-based swaps and liquidity pools", status: "Check contract, slippage and audits", source: "Protocol disclosure" },
  { name: "Global platform", type: "Overseas platform", features: "Availability, KYC, withdrawals and tax access vary", status: "Check India compliance and reporting", source: "Platform disclosure" },
  { name: "Crypto tax service", type: "Tax tooling", features: "Transaction imports, cost basis and tax reports", status: "Review calculations professionally", source: "Service disclosure" },
];

export const cryptoQuestions = ["What is cryptocurrency?", "How to buy Bitcoin in India?", "Is crypto legal in India?", "How is crypto taxed in India?", "What is 1% TDS on crypto?", "How to store crypto safely?", "Bitcoin versus Ethereum?", "What is a crypto wallet?", "What is staking?", "What is DeFi?", "What is a stablecoin?", "How to calculate crypto profit?"];
export const cryptoSources = [{ label: "Income Tax Department VDA guidance", href: "https://www.incometaxindia.gov.in/w/taxation-of-virtual-digital-asset-vda-" }, { label: "VDA TDS guidance", href: "https://www.incometaxindia.gov.in/w/tds-on-payment-for-the-transfer-of-virtual-digital-assets-vdas-" }, { label: "FIU-India VDA resources", href: "https://fiuindia.gov.in/files/Downloads/Downloads.html" }];
