export type StockSector = "Banking" | "IT" | "Energy" | "Auto" | "Pharma" | "FMCG" | "Defence" | "Railways" | "Telecom" | "Infrastructure" | "Metals" | "Power";
export type IndianStock = { slug: string; name: string; symbol: string; bseCode: string; isin: string; sector: StockSector; industry: string; exchange: "NSE" | "BSE" | "NSE/BSE"; price: number; change: number; marketCap: string; pe: number | null; pb: number | null; dividendYield: number; roe: number; roce: number; debtToEquity: number; revenueGrowth: number; profitGrowth: number; promoterHolding: number; fiiHolding: number; diiHolding: number; high52: number; low52: number; beta: number; summary: string; source: string; risk: string };

export const indianStocks: IndianStock[] = [
  { slug: "reliance", name: "Reliance Industries", symbol: "RELIANCE", bseCode: "500325", isin: "INE002A01018", sector: "Energy", industry: "Oil, gas, telecom and retail", exchange: "NSE/BSE", price: 1428.5, change: 1.24, marketCap: "₹19.3T", pe: 24.8, pb: 2.4, dividendYield: 0.35, roe: 9.8, roce: 10.7, debtToEquity: 0.42, revenueGrowth: 8.2, profitGrowth: 12.4, promoterHolding: 50.3, fiiHolding: 20.1, diiHolding: 17.8, high52: 1620, low52: 1140, beta: 1.12, summary: "Diversified Indian company with energy, digital services, retail and new-energy businesses.", source: "Reference fundamentals snapshot", risk: "Conglomerate complexity, capital intensity and sector-cycle risk" },
  { slug: "tcs", name: "Tata Consultancy Services", symbol: "TCS", bseCode: "532540", isin: "INE467B01029", sector: "IT", industry: "IT services", exchange: "NSE/BSE", price: 3650.2, change: -0.48, marketCap: "₹13.2T", pe: 27.6, pb: 13.4, dividendYield: 1.18, roe: 48.1, roce: 58.2, debtToEquity: 0.08, revenueGrowth: 7.4, profitGrowth: 8.1, promoterHolding: 71.7, fiiHolding: 12.6, diiHolding: 10.9, high52: 4592, low52: 3057, beta: 0.72, summary: "Large Indian IT-services company serving global enterprise technology clients.", source: "Reference fundamentals snapshot", risk: "Global IT spending, currency and concentration risk" },
  { slug: "hdfc-bank", name: "HDFC Bank", symbol: "HDFCBANK", bseCode: "500180", isin: "INE040A01034", sector: "Banking", industry: "Private-sector bank", exchange: "NSE/BSE", price: 1718.4, change: 0.62, marketCap: "₹13.1T", pe: 19.4, pb: 2.7, dividendYield: 1.05, roe: 15.1, roce: 0, debtToEquity: 0, revenueGrowth: 10.2, profitGrowth: 9.6, promoterHolding: 0, fiiHolding: 47.2, diiHolding: 28.3, high52: 1790, low52: 1363, beta: 0.88, summary: "Large private-sector bank with retail, corporate and digital banking operations.", source: "Reference fundamentals snapshot", risk: "Credit cycle, asset quality and interest-rate risk" },
  { slug: "icici-bank", name: "ICICI Bank", symbol: "ICICIBANK", bseCode: "532174", isin: "INE090A01021", sector: "Banking", industry: "Private-sector bank", exchange: "NSE/BSE", price: 1240.7, change: 0.94, marketCap: "₹8.7T", pe: 18.8, pb: 3.1, dividendYield: 0.72, roe: 17.2, roce: 0, debtToEquity: 0, revenueGrowth: 13.1, profitGrowth: 14.2, promoterHolding: 0, fiiHolding: 44.8, diiHolding: 30.1, high52: 1362, low52: 898, beta: 0.91, summary: "Private-sector bank with retail, business and institutional banking franchises.", source: "Reference fundamentals snapshot", risk: "Credit quality, provisioning and macroeconomic risk" },
  { slug: "infosys", name: "Infosys", symbol: "INFY", bseCode: "500209", isin: "INE009A01021", sector: "IT", industry: "IT services", exchange: "NSE/BSE", price: 1642.3, change: -0.22, marketCap: "₹6.8T", pe: 25.7, pb: 8.3, dividendYield: 2.15, roe: 31.6, roce: 40.7, debtToEquity: 0.09, revenueGrowth: 5.8, profitGrowth: 4.3, promoterHolding: 14.6, fiiHolding: 35.7, diiHolding: 30.4, high52: 1990, low52: 1352, beta: 0.78, summary: "Global IT-services and consulting company with a large export-oriented business.", source: "Reference fundamentals snapshot", risk: "Global demand, currency and client-spending risk" },
  { slug: "bharti-airtel", name: "Bharti Airtel", symbol: "BHARTIARTL", bseCode: "532454", isin: "INE397D01024", sector: "Telecom", industry: "Telecommunications", exchange: "NSE/BSE", price: 1850.8, change: 1.72, marketCap: "₹11.0T", pe: 34.2, pb: 8.1, dividendYield: 0.42, roe: 19.2, roce: 25.4, debtToEquity: 1.18, revenueGrowth: 12.6, profitGrowth: 20.1, promoterHolding: 52.1, fiiHolding: 24.1, diiHolding: 15.2, high52: 1980, low52: 1190, beta: 0.96, summary: "Telecom operator with mobile, broadband and enterprise connectivity businesses.", source: "Reference fundamentals snapshot", risk: "Leverage, competition and regulatory risk" },
  { slug: "larsen-toubro", name: "Larsen & Toubro", symbol: "LT", bseCode: "500510", isin: "INE018A01030", sector: "Infrastructure", industry: "Engineering and construction", exchange: "NSE/BSE", price: 3710.6, change: 1.18, marketCap: "₹5.1T", pe: 32.1, pb: 5.2, dividendYield: 0.72, roe: 15.4, roce: 17.8, debtToEquity: 1.02, revenueGrowth: 15.3, profitGrowth: 16.8, promoterHolding: 0, fiiHolding: 21.7, diiHolding: 38.2, high52: 3980, low52: 2450, beta: 1.08, summary: "Engineering, construction, technology and infrastructure company with a diversified order book.", source: "Reference fundamentals snapshot", risk: "Execution, working capital and project-cycle risk" },
  { slug: "sun-pharma", name: "Sun Pharmaceutical Industries", symbol: "SUNPHARMA", bseCode: "524715", isin: "INE044A01036", sector: "Pharma", industry: "Pharmaceuticals", exchange: "NSE/BSE", price: 1688.9, change: 0.76, marketCap: "₹4.1T", pe: 39.8, pb: 7.2, dividendYield: 0.55, roe: 17.8, roce: 19.6, debtToEquity: 0.11, revenueGrowth: 11.7, profitGrowth: 24.5, promoterHolding: 54.5, fiiHolding: 17.1, diiHolding: 18.9, high52: 1960, low52: 1020, beta: 0.66, summary: "Pharmaceutical company with domestic, specialty and global formulations businesses.", source: "Reference fundamentals snapshot", risk: "Regulatory, product and litigation risk" },
  { slug: "maruti-suzuki", name: "Maruti Suzuki India", symbol: "MARUTI", bseCode: "532500", isin: "INE585B01010", sector: "Auto", industry: "Passenger vehicles", exchange: "NSE/BSE", price: 12540, change: -0.31, marketCap: "₹3.9T", pe: 29.1, pb: 4.1, dividendYield: 0.67, roe: 14.5, roce: 18.2, debtToEquity: 0.02, revenueGrowth: 12.8, profitGrowth: 13.6, promoterHolding: 56.4, fiiHolding: 18.3, diiHolding: 17.5, high52: 13680, low52: 9250, beta: 0.84, summary: "India-focused passenger-vehicle manufacturer with a wide distribution network.", source: "Reference fundamentals snapshot", risk: "Consumer demand, commodity and competition risk" },
  { slug: "sbi", name: "State Bank of India", symbol: "SBIN", bseCode: "500112", isin: "INE062A01020", sector: "Banking", industry: "Public-sector bank", exchange: "NSE/BSE", price: 835.4, change: 1.03, marketCap: "₹7.5T", pe: 10.9, pb: 1.6, dividendYield: 1.67, roe: 17.1, roce: 0, debtToEquity: 0, revenueGrowth: 9.4, profitGrowth: 15.8, promoterHolding: 57.5, fiiHolding: 11.3, diiHolding: 22.7, high52: 912, low52: 555, beta: 1.02, summary: "India's largest public-sector bank with retail, corporate and government-linked banking operations.", source: "Reference fundamentals snapshot", risk: "Credit cycle, policy and asset-quality risk" },
  { slug: "tata-steel", name: "Tata Steel", symbol: "TATASTEEL", bseCode: "500470", isin: "INE081A01020", sector: "Metals", industry: "Steel", exchange: "NSE/BSE", price: 168.2, change: 2.44, marketCap: "₹2.1T", pe: 29.5, pb: 2.2, dividendYield: 1.14, roe: 5.2, roce: 7.6, debtToEquity: 0.91, revenueGrowth: -3.8, profitGrowth: 8.4, promoterHolding: 33.6, fiiHolding: 19.4, diiHolding: 20.2, high52: 190, low52: 101, beta: 1.27, summary: "Steel producer exposed to domestic infrastructure demand and global metal cycles.", source: "Reference fundamentals snapshot", risk: "Commodity prices, leverage and global-cycle risk" },
];

export const nifty50Symbols = ["reliance", "tcs", "hdfc-bank", "icici-bank", "infosys", "bharti-airtel", "larsen-toubro", "sun-pharma", "maruti-suzuki", "sbi", "tata-steel"];
export const stockSectors: StockSector[] = ["Banking", "IT", "Energy", "Auto", "Pharma", "FMCG", "Defence", "Railways", "Telecom", "Infrastructure", "Metals", "Power"];
export const brokerCategories = ["Discount broker", "Full-service broker", "Bank-backed broker", "API-first broker", "Long-term investing platform"];
export const stockBrokers = [
  { name: "SEBI-registered broker directory", type: "Verification resource", features: "Registration number, exchange membership and intermediary search", link: "https://www.sebi.gov.in/sebiweb/other/OtherAction.do?doRecognisedFpi=yes&intmId=30", source: "SEBI official database" },
  { name: "NSE investor resources", type: "Exchange resource", features: "Market data, filings, indices, investor protection and education", link: "https://www.nseindia.com/", source: "NSE official website" },
  { name: "BSE investor resources", type: "Exchange resource", features: "Market data, Sensex, filings, corporate actions and investor services", link: "https://www.bseindia.com/", source: "BSE official website" },
  { name: "NSDL and CDSL", type: "Depositories", features: "Demat holdings, statements, corporate-action credits and transmission", link: "https://www.sebi.gov.in/", source: "SEBI investor resources" },
];
export const stockNews = [
  { title: "Track exchange filings, results and corporate actions from official sources", tag: "Corporate filings", source: "NSE/BSE", href: "https://www.nseindia.com/companies-listing/corporate-filings-announcements?tabIndex=equity" },
  { title: "Use SEBI investor education before opening a demat or trading account", tag: "Investor education", source: "SEBI Investor", href: "https://investor.sebi.gov.in/iematerial.html" },
  { title: "Review broker registration and investor-charter information", tag: "Broker safety", source: "SEBI", href: "https://www.sebi.gov.in/sebiweb/other/OtherAction.do?doRecognisedFpi=yes&intmId=30" },
];
export const stockSources = [{ label: "Nifty Indices", href: "https://www.niftyindices.com/" }, { label: "NSE corporate filings", href: "https://www.nseindia.com/companies-listing/corporate-filings-announcements?tabIndex=equity" }, { label: "SEBI investor education", href: "https://investor.sebi.gov.in/iematerial.html" }, { label: "SEBI registered brokers", href: "https://www.sebi.gov.in/sebiweb/other/OtherAction.do?doRecognisedFpi=yes&intmId=30" }];
