export type InsuranceCategoryKey = "health" | "term" | "life" | "car" | "bike" | "travel" | "personal-accident" | "home" | "retirement" | "ulip";
export type InsuranceProviderType = "life" | "general" | "health" | "broker";

export type InsuranceCategory = {
  key: InsuranceCategoryKey;
  name: string;
  shortName: string;
  summary: string;
  audience: string;
  color: string;
  benefits: string[];
  disadvantages: string[];
  questions: string[];
  route: string;
};

export type InsuranceProvider = {
  slug: string;
  name: string;
  type: InsuranceProviderType;
  segments: string[];
  summary: string;
  website: string;
  metrics: Array<{ label: string; value: string; source: string }>;
  sourceDate: string;
};

export const insuranceCategories: InsuranceCategory[] = [
  { key: "health", name: "Health insurance", shortName: "Health", summary: "Protect savings from hospitalization and treatment costs.", audience: "Individuals, families and senior citizens", color: "#34d399", benefits: ["Cashless treatment at network hospitals", "Protection from large hospitalization bills", "Coverage can be tailored for individuals or families", "Optional critical illness, maternity and top-up benefits"], disadvantages: ["Waiting periods for pre-existing diseases and selected treatments", "Room-rent limits, co-payments, deductibles and exclusions", "Premiums can increase with age and medical inflation", "Non-disclosure can create claim disputes"], questions: ["Which health insurance is best for parents?", "What is a family floater?", "How long is the waiting period?", "What does cashless mean?"], route: "/insurance/health" },
  { key: "term", name: "Term insurance", shortName: "Term life", summary: "Create income protection for dependents if the insured dies.", audience: "Working adults, parents and borrowers", color: "#60a5fa", benefits: ["Large life cover at a relatively lower premium", "Protects dependents and outstanding loans", "Simple protection-focused product", "Optional riders for accident or critical illness"], disadvantages: ["Standard term plans have no maturity payout", "Premium depends on age, health, smoking and occupation", "Incorrect disclosures may affect claims", "Cover can become inadequate as income and inflation rise"], questions: ["How much term insurance do I need?", "Term insurance vs ULIP?", "Do smokers pay more?", "What happens to the nominee?"], route: "/insurance/term" },
  { key: "life", name: "Life insurance", shortName: "Life", summary: "Combine life protection with savings, income or legacy goals.", audience: "Families, savers and retirement planners", color: "#a78bfa", benefits: ["Death benefit for nominees", "Some products provide guaranteed or structured payouts", "Can support retirement and legacy planning", "Different products suit different time horizons"], disadvantages: ["Savings products may be complex and less liquid", "Charges and surrender rules vary by product", "Returns and guarantees must be read from the policy wording", "Investment and protection goals may be better separated"], questions: ["LIC vs private life insurance?", "Endowment vs term insurance?", "What is a money-back plan?", "What is a nominee?"], route: "/insurance/life" },
  { key: "car", name: "Car insurance", shortName: "Car", summary: "Cover third-party liability and damage to your vehicle.", audience: "Car owners and drivers", color: "#f59e0b", benefits: ["Third-party liability protection", "Own-damage, theft and accident protection", "Optional zero-depreciation and roadside assistance", "Cashless garage access where available"], disadvantages: ["Deductibles and depreciation reduce claim payout", "IDV affects the vehicle-damage settlement", "Claims can affect no-claim bonus", "Policy exclusions and driver conditions apply"], questions: ["Third-party vs comprehensive insurance?", "How is IDV calculated?", "What is zero depreciation?", "How do I renew expired insurance?"], route: "/insurance/car" },
  { key: "bike", name: "Two-wheeler insurance", shortName: "Bike", summary: "Protect riders, vehicles and third parties on Indian roads.", audience: "Bike and scooter owners", color: "#f472b6", benefits: ["Mandatory third-party liability cover", "Protection against theft and accidental damage", "Personal accident cover options", "Online renewal and policy download"], disadvantages: ["Third-party cover does not repair your own vehicle", "Deductibles and depreciation affect claims", "Lapses may require inspection", "Rider and licence conditions matter"], questions: ["How do I check bike insurance?", "What is own-damage cover?", "How does no-claim bonus work?", "What documents are required?"], route: "/insurance/bike" },
  { key: "travel", name: "Travel insurance", shortName: "Travel", summary: "Reduce the financial impact of medical and travel emergencies.", audience: "Domestic travellers, students and international travellers", color: "#38bdf8", benefits: ["Emergency medical coverage", "Trip cancellation and delay support", "Baggage and passport loss benefits", "Useful for international travel requirements"], disadvantages: ["Destination, activity and pre-existing-condition exclusions", "Documentation is important for claims", "Coverage limits differ widely", "Travel insurance does not remove every travel risk"], questions: ["Is travel insurance mandatory?", "What does Schengen insurance cover?", "Does it cover flight cancellation?", "Are adventure sports covered?"], route: "/insurance/travel" },
  { key: "personal-accident", name: "Personal accident", shortName: "Accident", summary: "Provide a benefit for accidental death or disability.", audience: "Workers, commuters and families", color: "#fb7185", benefits: ["Usually affordable protection", "Lump-sum disability benefits", "Can supplement health or term insurance", "Useful for income-impacting accidents"], disadvantages: ["Does not replace health insurance for ordinary illness", "Accident definitions and exclusions matter", "Permanent disability assessment can be complex", "Benefit amounts may not match income needs"], questions: ["What counts as an accident?", "What is permanent disability?", "Is personal accident included in motor insurance?", "How much cover is enough?"], route: "/insurance/personal-accident" },
  { key: "home", name: "Home insurance", shortName: "Home", summary: "Protect the structure and contents of a home from listed risks.", audience: "Homeowners, tenants and landlords", color: "#4ade80", benefits: ["Protection for structure and contents", "Cover for selected fire, theft and natural perils", "Optional landlord or tenant extensions", "Can protect a major household asset"], disadvantages: ["Underinsurance can reduce claim payments", "Not every natural event or item is covered", "Valuation and proof of ownership may be required", "Premium and cover depend on location and construction"], questions: ["Is home insurance worth it?", "Does it cover floods and earthquakes?", "Can tenants buy contents insurance?", "How is property value assessed?"], route: "/insurance/home" },
  { key: "retirement", name: "Retirement and annuity", shortName: "Retirement", summary: "Plan predictable income for life after employment.", audience: "Pre-retirees and retirement planners", color: "#22c55e", benefits: ["Potential regular income stream", "Supports long-term retirement planning", "Some products offer joint-life or return-of-premium options", "Can complement EPF, NPS and investments"], disadvantages: ["Liquidity and surrender terms can be restrictive", "Inflation can reduce purchasing power", "Annuity rates and payout choices need comparison", "Tax treatment depends on current rules"], questions: ["How much retirement income do I need?", "Immediate vs deferred annuity?", "What is joint-life annuity?", "How does inflation affect retirement?"], route: "/insurance/retirement" },
  { key: "ulip", name: "ULIP and investment-linked insurance", shortName: "ULIP", summary: "Combine life cover with market-linked investment choices.", audience: "Long-term investors who understand market risk", color: "#c084fc", benefits: ["Insurance and investment in one product", "Choice of funds in many products", "Long-term disciplined investing", "Some switching and allocation flexibility"], disadvantages: ["Market risk is borne by the policyholder", "Charges and product structure can be complex", "Not suitable for short-term goals", "Returns are not guaranteed unless explicitly stated"], questions: ["ULIP vs term insurance?", "What charges apply?", "Can I withdraw early?", "Who bears the investment risk?"], route: "/insurance/ulip" },
];

export const insuranceProviders: InsuranceProvider[] = [
  { slug: "lic", name: "Life Insurance Corporation of India", type: "life", segments: ["Life", "Term", "Savings", "Pension"], summary: "India's largest life insurer by premium share, with a broad life and pension product range.", website: "https://licindia.in", metrics: [{ label: "Life premium share", value: "57.02%", source: "DFS Annual Report 2025–26; FY 2024–25" }, { label: "Category", value: "Life insurer", source: "IRDAI" }], sourceDate: "FY 2024–25" },
  { slug: "sbi-life", name: "SBI Life", type: "life", segments: ["Life", "Term", "Savings", "Pension"], summary: "A major private life insurer with protection, savings and retirement products.", website: "https://www.sbilife.co.in", metrics: [{ label: "New business share", value: "8.14%", source: "IRDAI life insurer statement; FY 2024–25" }, { label: "Category", value: "Life insurer", source: "IRDAI" }], sourceDate: "FY 2024–25" },
  { slug: "hdfc-life", name: "HDFC Life", type: "life", segments: ["Life", "Term", "ULIP", "Retirement"], summary: "A large private life insurer covering protection, investment-linked and retirement needs.", website: "https://www.hdfclife.com", metrics: [{ label: "Category", value: "Life insurer", source: "IRDAI" }, { label: "Products", value: "Term, savings and retirement", source: "Provider website" }], sourceDate: "FY 2024–25" },
  { slug: "star-health", name: "Star Health", type: "health", segments: ["Health", "Senior citizen", "Family", "Personal accident"], summary: "A prominent standalone health insurer with retail health products.", website: "https://www.starhealth.in", metrics: [{ label: "Category", value: "Standalone health insurer", source: "IRDAI" }, { label: "Focus", value: "Retail health insurance", source: "Provider website" }], sourceDate: "FY 2024–25" },
  { slug: "niva-bupa", name: "Niva Bupa Health Insurance", type: "health", segments: ["Health", "Family", "Senior citizen", "Top-up"], summary: "A standalone health insurer offering individual, family and top-up products.", website: "https://www.nivabupa.com", metrics: [{ label: "Category", value: "Standalone health insurer", source: "IRDAI" }, { label: "Focus", value: "Retail health insurance", source: "Provider website" }], sourceDate: "FY 2024–25" },
  { slug: "care-health", name: "Care Health Insurance", type: "health", segments: ["Health", "Family", "Senior citizen", "Critical illness"], summary: "A health-focused insurer with retail, family and specialised health products.", website: "https://www.careinsurance.com", metrics: [{ label: "Category", value: "Standalone health insurer", source: "IRDAI" }, { label: "Focus", value: "Retail health insurance", source: "Provider website" }], sourceDate: "FY 2024–25" },
  { slug: "icici-lombard", name: "ICICI Lombard", type: "general", segments: ["Health", "Car", "Bike", "Travel", "Home"], summary: "A large private general insurer across health, motor and other general insurance lines.", website: "https://www.icicilombard.com", metrics: [{ label: "General insurance share", value: "8.91%", source: "IRDAI non-life flash figures; FY 2024–25" }, { label: "Category", value: "General insurer", source: "IRDAI" }], sourceDate: "FY 2024–25" },
  { slug: "hdfc-ergo", name: "HDFC ERGO", type: "general", segments: ["Health", "Car", "Bike", "Travel", "Home"], summary: "A private general insurer active across health, motor, travel and property protection.", website: "https://www.hdfcergo.com", metrics: [{ label: "Category", value: "General insurer", source: "IRDAI" }, { label: "Segments", value: "Health and motor", source: "Provider website" }], sourceDate: "FY 2024–25" },
  { slug: "new-india-assurance", name: "New India Assurance", type: "general", segments: ["Health", "Car", "Bike", "Home", "Commercial"], summary: "A public-sector general insurer with broad non-life product coverage.", website: "https://www.newindia.co.in", metrics: [{ label: "Category", value: "General insurer", source: "IRDAI" }, { label: "Segments", value: "Health, motor and commercial", source: "Provider website" }], sourceDate: "FY 2024–25" },
  { slug: "acko", name: "ACKO", type: "general", segments: ["Car", "Bike", "Health", "Travel"], summary: "A digital-first general insurer with online-focused motor and other products.", website: "https://www.acko.com", metrics: [{ label: "Category", value: "General insurer", source: "IRDAI" }, { label: "Distribution", value: "Digital-first", source: "Provider website" }], sourceDate: "FY 2024–25" },
  { slug: "policybazaar", name: "Policybazaar", type: "broker", segments: ["Health", "Term", "Car", "Bike", "Travel"], summary: "An insurance comparison and distribution platform, not an insurer.", website: "https://www.policybazaar.com", metrics: [{ label: "Category", value: "Insurance intermediary", source: "Company website" }, { label: "Role", value: "Comparison and distribution", source: "Company website" }], sourceDate: "Current reference" },
];

export function getInsuranceCategory(value: string | null | undefined) {
  return insuranceCategories.find((item) => item.key === value?.toLowerCase()) ?? null;
}

export function getInsuranceProvider(value: string | null | undefined) {
  return insuranceProviders.find((item) => item.slug === value?.toLowerCase()) ?? null;
}

export const insuranceSources = [
  { label: "IRDAI Health Insurance guidance", href: "https://irdai.gov.in/health-dept" },
  { label: "IRDAI Motor Insurance guidance", href: "https://irdai.gov.in/web/policy-holder/motor-insurance" },
  { label: "IRDAI policyholder grievance guidance", href: "https://irdai.gov.in/grievance-redressal-mechanism1" },
  { label: "IRDAI 2024 regulations", href: "https://irdai.gov.in/consolidated-gazette-notified-regulations" },
];
