export type MetalsGuide = { title: string; summary: string; sections: { title: string; text: string }[]; sources: { title: string; url: string }[]; reviewedAt: string };
const methodology = { title: "Provider documentation", url: "https://gold-api.com/docs" };
const bis = { title: "BIS consumer protection", url: "https://www.bis.gov.in/hallmarking-overview/consumer-protection/?lang=en" };
export const metalsGuides: Record<string, MetalsGuide> = {
  hallmarking: { title: "Gold purity, hallmarking and HUID", summary: "Read purity declarations and use official verification resources before buying.", reviewedAt: "2026-09-08", sources: [bis], sections: [
    { title: "Karat is a proportion, not a price", text: "The theoretical gold fraction is karat divided by 24: 22K is about 91.67% and 18K is 75%. A purity label does not tell you the making charge, stone value or achievable resale price. Calculators estimate declared fine-metal content; they do not assay an item." },
    { title: "Use official verification", text: "Use BIS consumer guidance and the official BIS Care resources linked by BIS to check hallmarking information and HUID details. Match the physical item, seller and invoice information; a screenshot supplied by a seller is not independent verification. Requirements and exemptions can change, so consult the current official guidance for the product you are buying." },
    { title: "Keep a purchase record", text: "Ask for itemised weight, declared purity and charges. Retain the invoice and seller contact information. If information conflicts, resolve it with the seller or the appropriate official grievance channel before relying on the quotation." },
  ] },
  "price-basis": { title: "Retail, spot and futures: why metal prices differ", summary: "Compare like-for-like quotations before comparing numbers.", reviewedAt: "2026-09-08", sources: [methodology, { title: "MCX data subscriptions", url: "https://classic.mcxindia.com/technology/datafeed/who-can-subscribe-to-datafeed" }], sections: [
    { title: "Three different questions", text: "A retail quotation describes an offer from a seller for a specified product. A spot reference is a market benchmark, not necessarily an executable consumer price. A futures quotation refers to a particular contract and expiry. Currency, unit, market and observation time must match before comparing them." },
    { title: "A conversion is not a local quote", text: "Converting a USD-per-troy-ounce reference into rupees per gram changes the currency and unit only. It does not add local availability, taxes, fabrication charges or dealer margins. We label such values converted references, not Mumbai or Chennai retail prices." },
    { title: "Price is not investment quality", text: "A kilogram of copper and a gram of gold are not comparable unit prices. Even after mass conversion, supply, industrial use, volatility, storage and transaction costs differ. This site does not rank metals as better investments from their nominal price." },
  ] },
  invoice: { title: "Understand a jewellery invoice", summary: "Separate metal weight from stones and inspect how each charge is calculated.", reviewedAt: "2026-09-08", sources: [bis], sections: [
    { title: "Start with net weight", text: "Subtract non-metal weight from gross weight before valuing the metal. Ask whether a quoted rate already corresponds to the selected purity. Applying a 22/24 factor to an already-22K rate would incorrectly reduce the metal value a second time." },
    { title: "Identify the charge basis", text: "Making charges may be a percentage, an amount per gram, a fixed amount or a stated combination. Our purchase tool adds the methods you enter. The comparison tool treats them as alternatives. Enter a wastage charge only if it appears on your quotation; do not invent one to match a bill." },
    { title: "Tax and discounts are explicit assumptions", text: "Our manual tool subtracts the entered discount before applying the user-entered tax percentage to the subtotal. Actual tax treatment depends on the transaction. This is a declared arithmetic model, not a universal GST rule. Stone services or other charges may need separate treatment. An invoice difference is a prompt to ask questions, not proof of wrongdoing." },
  ] },
  "coins-bars-jewellery": { title: "Coins, bars or jewellery? Compare purchase costs", summary: "Choose according to use and inspect the complete purchase and resale terms.", reviewedAt: "2026-09-08", sources: [bis], sections: [
    { title: "Compare the complete item", text: "Jewellery has design and fabrication value in addition to its metal. Coins and bars can also carry minting, packaging and dealer premiums. Compare a written all-in quotation, not only the displayed metal rate." },
    { title: "Ask about resale before purchase", text: "Find out whether a seller repurchases the product, how purity is assessed and which charges are non-recoverable. A purchase price is not a buyback guarantee. Keep packaging and proof of purchase where the seller's terms require them." },
    { title: "Consider practical costs", text: "Storage, insurance, transport and future assay fees can affect the economics of physical ownership. This guide does not recommend an investment allocation or promise a return." },
  ] },
  exchange: { title: "Old-gold exchange and buyback estimates", summary: "Model a dealer's stated offer without mistaking it for a guaranteed payout.", reviewedAt: "2026-09-08", sources: [bis], sections: [
    { title: "Use a buyback rate", text: "Enter the dealer's quoted rate for the assessed purity, not the new-jewellery retail price. Exclude stones and other non-metal weight. Explain any difference between declared and assessed purity with the dealer." },
    { title: "Document deductions", text: "The exchange tool applies the percentage deduction to the metal value and then subtracts the fixed deduction. Enter only documented deductions. It rejects negative net weight and deductions exceeding proceeds rather than showing an impossible offer." },
    { title: "Compare written offers", text: "Request comparable offers with the same net weight and assessed purity. Account for whether the proceeds are cash, store credit or conditional on a new purchase. The estimator does not certify an assay or legally bind the dealer." },
  ] },
  drivers: { title: "Understanding gold and silver price movements", summary: "Read market context without treating a headline as a guaranteed explanation.", reviewedAt: "2026-09-08", sources: [{ title: "World Gold Council research and data", url: "https://www.gold.org/goldhub" }], sections: [
    { title: "Separate observation from explanation", text: "First check the price basis, period and source of a reported move. A rupee-denominated reference can change because of the underlying metal, the exchange rate or both. Two observations at different times may not describe the same movement." },
    { title: "Read context carefully", text: "Market reports discuss interest rates, currencies, investment demand, industrial demand and supply. These are contexts to investigate, not proof that one event caused a specific tick. Link to original reporting and distinguish attributed analysis from a measured fact." },
    { title: "Avoid extrapolating a short series", text: "Being above or below a recent average is descriptive, not a reliable buy/wait rule. Missing observations, changing quote sources and charges can distort comparisons. Our tools do not forecast guaranteed future prices." },
  ] },
  wedding: { title: "Wedding and festival jewellery budgeting", summary: "Plan spending from explicit quotations rather than a forecast of tomorrow's gold rate.", reviewedAt: "2026-09-08", sources: [bis], sections: [
    { title: "Set the total budget first", text: "Include metal, stones, fabrication and applicable taxes in each item quotation. The three-group planner can represent, for example, major jewellery, smaller items and gifts. These labels are your planning groups, not seller packages." },
    { title: "Keep quantity and assumptions visible", text: "Use the budget-to-gold tool to explore how the same budget changes with a different rate or making charge. It assumes no stones and no fees beyond those entered. Set aside any contingency outside the maximum-weight result rather than treating it as a purchase commitment." },
    { title: "Save and revisit", text: "Saved estimates retain your inputs, not a locked offer. Before buying, obtain an updated quotation and compare the full bill. Promotions and festival timing do not guarantee a lower all-in price." },
  ] },
  methodology: { title: "Metals data, calculations and corrections", summary: "What our numbers mean, what they exclude and how to report a problem.", reviewedAt: "2026-09-08", sources: [methodology, { title: "Gold API terms", url: "https://gold-api.com/terms" }, { title: "Frankfurter reference FX", url: "https://frankfurter.dev/" }], sections: [
    { title: "Sources and availability", text: "Gold, silver, platinum and copper references use Gold API with Frankfurter daily USD/INR; provider terms reviewed on 8 September 2026. Gold API documents website use. These are converted provider references, not local jeweller quotations or live FX. Copper uses the HG benchmark and standard USD-per-pound convention; the provider does not supply explicit units or a contract month. We convert pounds to kilograms using 0.45359237 kg per pound, not the precious-metal troy-ounce formula. Verify the copper convention independently before use. Deployments can switch the feeds off. Legacy retail scraping and historical redistribution remain disabled. Missing data never prevents manual calculations." },
    { title: "Conversion and timestamps", text: "Converted INR per gram = USD per troy ounce × USD/INR ÷ 31.1034768. We retain the metal observation timestamp, FX date and retrieval time separately. An unknown observation time is not replaced by the time we fetched the response. Currency conversion does not establish a local retail quotation." },
    { title: "Freshness and history", text: "The reference cache refreshes at most every five minutes; daily FX is cached for one hour. A metal observation over 20 minutes old or FX over four days old is marked stale. Metal observations over 72 hours old, unknown observation times or FX over seven days old are not used as prices. These are disclosure policies, not exchange-session definitions. History must preserve gaps and actual coverage; current FX is never applied across historical INR observations." },
    { title: "Manual assumptions and precision", text: "Calculator results use your inputs. Prices and taxes are not silently prefilled. Money is rounded to two decimals at output; intermediate arithmetic uses JavaScript numeric precision and is an estimate, not settlement accounting. Optional zero charges mean excluded assumptions. Fine-metal conversion is not an assay. Annualised return is a mathematical transformation, not a promise." },
    { title: "Privacy and corrections", text: "Guest estimates are device-local; account estimates use private authenticated storage. Tool sharing excludes your financial inputs. No personal inputs are sent to analytics by these tools. To report a problem, email phaneesh19@gmail.com with the page URL, observation time and a description. Do not send passwords or sensitive invoices. We will investigate source and calculation issues; no response deadline is promised." },
  ] },
};
