export type FundType = "equity" | "debt" | "hybrid" | "index" | "elss" | "liquid" | "international" | "solution";
export type RiskLevel = "Low" | "Low to Moderate" | "Moderate" | "Moderately High" | "High" | "Very High";

export type MutualFund = {
  slug: string; schemeCode: string; isin: string; name: string; amc: string; category: FundType; subCategory: string; plan: "Direct" | "Regular"; option: "Growth" | "IDCW"; nav: number; navDate: string; returns: { oneYear: number; threeYear: number; fiveYear: number; tenYear: number }; risk: RiskLevel; expenseRatio: number; aum: string; minSip: number; minInvestment: number; exitLoad: string; benchmark: string; manager: string; inception: string; summary: string; source: string;
};

export type FundCategory = { key: FundType; name: string; summary: string; audience: string; color: string; route: string; benefits: string[]; disadvantages: string[] };

export const fundCategories: FundCategory[] = [
  { key: "equity", name: "Equity funds", summary: "Funds that primarily invest in shares for long-term growth with market volatility.", audience: "Long-term growth investors", color: "#a78bfa", route: "/mutual-funds/equity", benefits: ["Diversified equity exposure", "Long-term wealth-creation potential", "SIP-friendly structure"], disadvantages: ["High short-term volatility", "Capital is not guaranteed", "Sector and market-cycle risks"] },
  { key: "debt", name: "Debt funds", summary: "Funds investing in fixed-income securities such as bonds, T-bills and money-market instruments.", audience: "Income and capital-stability seekers", color: "#38bdf8", route: "/mutual-funds/debt", benefits: ["Exposure to fixed-income instruments", "Several duration choices", "Can support portfolio diversification"], disadvantages: ["Credit and interest-rate risk", "Returns are not guaranteed", "Tax treatment varies by scheme"] },
  { key: "hybrid", name: "Hybrid funds", summary: "Funds combining equity and fixed income to balance growth and portfolio volatility.", audience: "Investors seeking blended allocation", color: "#34d399", route: "/mutual-funds/hybrid", benefits: ["Multi-asset exposure", "Automatic allocation inside the scheme", "May smooth volatility versus pure equity"], disadvantages: ["Allocation can change", "Still carries market risk", "Category labels can hide different strategies"] },
  { key: "index", name: "Index funds and ETFs", summary: "Passive funds designed to track an index before costs and tracking difference.", audience: "Low-cost passive investors", color: "#60a5fa", route: "/mutual-funds/index-funds", benefits: ["Transparent benchmark objective", "Usually simple to understand", "Can have lower costs"], disadvantages: ["Cannot outperform the tracked index before costs", "Tracking error matters", "ETFs require exchange liquidity and a demat account"] },
  { key: "elss", name: "ELSS tax-saving funds", summary: "Equity-linked schemes with a statutory lock-in and tax treatment subject to current rules.", audience: "Eligible tax-saving investors", color: "#f59e0b", route: "/mutual-funds/elss", benefits: ["Equity growth potential", "Shortest statutory lock-in among common tax-saving investments", "SIP-compatible"], disadvantages: ["Market risk", "Three-year lock-in applies to each SIP instalment", "Tax benefit depends on applicable regime and rules"] },
  { key: "liquid", name: "Liquid and money-market funds", summary: "Short-duration funds holding money-market and very short-term instruments.", audience: "Short-term cash management", color: "#22c55e", route: "/mutual-funds/liquid-funds", benefits: ["Short duration exposure", "Open-ended liquidity in normal conditions", "Useful for temporary cash allocation"], disadvantages: ["Not a bank deposit", "Returns vary with market rates", "Small credit and liquidity risks remain"] },
  { key: "international", name: "International funds", summary: "Funds providing exposure to securities or funds outside India and related currency movements.", audience: "Diversification beyond India", color: "#f472b6", route: "/mutual-funds/international-funds", benefits: ["Geographic diversification", "Access to overseas companies and themes", "Currency diversification"], disadvantages: ["Currency and foreign-market risk", "Tax and regulatory complexity", "International fund availability can change"] },
  { key: "solution", name: "Solution-oriented funds", summary: "Retirement and children-focused funds designed around long-term objectives and scheme conditions.", audience: "Goal-based long-term investors", color: "#fb7185", route: "/mutual-funds/solution-oriented", benefits: ["Goal-oriented framing", "Long investment horizon", "Can support disciplined contributions"], disadvantages: ["Lock-in or exit conditions may apply", "Goals still need broader planning", "Market risk remains"] },
];

export const mutualFunds: MutualFund[] = [
  { slug: "axis-bluechip-direct-growth", schemeCode: "AXIS001", isin: "INF846K01DP8", name: "Axis Bluechip Fund", amc: "Axis Mutual Fund", category: "equity", subCategory: "Large Cap", plan: "Direct", option: "Growth", nav: 58.42, navDate: "23 Aug 2026", returns: { oneYear: 14.8, threeYear: 16.2, fiveYear: 13.7, tenYear: 12.9 }, risk: "Very High", expenseRatio: 0.64, aum: "₹32,410 Cr", minSip: 500, minInvestment: 500, exitLoad: "1% within 12 months", benchmark: "Nifty 100 TRI", manager: "Reference manager profile", inception: "2010", summary: "Large-cap equity reference fund focused on established Indian companies.", source: "AMC factsheet reference" },
  { slug: "hdfc-flexi-cap-direct-growth", schemeCode: "HDFC002", isin: "INF179K01BB8", name: "HDFC Flexi Cap Fund", amc: "HDFC Mutual Fund", category: "equity", subCategory: "Flexi Cap", plan: "Direct", option: "Growth", nav: 1842.31, navDate: "23 Aug 2026", returns: { oneYear: 19.1, threeYear: 21.4, fiveYear: 18.2, tenYear: 15.6 }, risk: "Very High", expenseRatio: 0.72, aum: "₹68,120 Cr", minSip: 500, minInvestment: 500, exitLoad: "1% within 12 months", benchmark: "Nifty 500 TRI", manager: "Reference manager profile", inception: "1995", summary: "Diversified equity reference fund with flexibility across market capitalisations.", source: "AMC factsheet reference" },
  { slug: "sbi-nifty-index-direct-growth", schemeCode: "SBI003", isin: "INF200K01QX5", name: "SBI Nifty Index Fund", amc: "SBI Mutual Fund", category: "index", subCategory: "Index Fund", plan: "Direct", option: "Growth", nav: 242.18, navDate: "23 Aug 2026", returns: { oneYear: 13.4, threeYear: 15.7, fiveYear: 14.1, tenYear: 12.4 }, risk: "Very High", expenseRatio: 0.18, aum: "₹9,840 Cr", minSip: 500, minInvestment: 500, exitLoad: "0.25% within 15 days", benchmark: "Nifty 50 TRI", manager: "Passive management", inception: "2002", summary: "Low-cost passive reference fund designed to track the Nifty 50.", source: "AMC factsheet reference" },
  { slug: "parag-parikh-flexi-cap-direct-growth", schemeCode: "PPF004", isin: "INF879O01027", name: "Parag Parikh Flexi Cap Fund", amc: "PPFAS Mutual Fund", category: "equity", subCategory: "Flexi Cap", plan: "Direct", option: "Growth", nav: 78.96, navDate: "23 Aug 2026", returns: { oneYear: 17.8, threeYear: 22.1, fiveYear: 20.4, tenYear: 18.1 }, risk: "Very High", expenseRatio: 0.63, aum: "₹74,220 Cr", minSip: 1000, minInvestment: 1000, exitLoad: "2% within 365 days", benchmark: "Nifty 500 TRI", manager: "Reference manager profile", inception: "2013", summary: "Diversified equity reference fund with domestic and overseas exposure.", source: "AMC factsheet reference" },
  { slug: "icici-prudential-balanced-advantage-direct-growth", schemeCode: "ICI005", isin: "INF109K01Z44", name: "ICICI Prudential Balanced Advantage Fund", amc: "ICICI Prudential Mutual Fund", category: "hybrid", subCategory: "Dynamic Asset Allocation", plan: "Direct", option: "Growth", nav: 72.46, navDate: "23 Aug 2026", returns: { oneYear: 12.7, threeYear: 15.2, fiveYear: 13.5, tenYear: 12.2 }, risk: "Moderately High", expenseRatio: 0.68, aum: "₹61,730 Cr", minSip: 100, minInvestment: 100, exitLoad: "1% within 12 months", benchmark: "Custom hybrid benchmark", manager: "Reference manager profile", inception: "2006", summary: "Hybrid reference fund using a dynamic equity and fixed-income allocation approach.", source: "AMC factsheet reference" },
  { slug: "kotak-liquid-direct-growth", schemeCode: "KOT006", isin: "INF174K01LS8", name: "Kotak Liquid Fund", amc: "Kotak Mahindra Mutual Fund", category: "liquid", subCategory: "Liquid Fund", plan: "Direct", option: "Growth", nav: 4218.75, navDate: "23 Aug 2026", returns: { oneYear: 6.8, threeYear: 6.4, fiveYear: 5.7, tenYear: 6.1 }, risk: "Low to Moderate", expenseRatio: 0.16, aum: "₹18,930 Cr", minSip: 100, minInvestment: 100, exitLoad: "Nil after 7 days", benchmark: "Nifty 1D Rate Index", manager: "Reference manager profile", inception: "2000", summary: "Short-duration debt reference fund for temporary cash allocation.", source: "AMC factsheet reference" },
  { slug: "quant-elss-tax-saver-direct-growth", schemeCode: "QNT007", isin: "INF966L01234", name: "Quant ELSS Tax Saver Fund", amc: "Quant Mutual Fund", category: "elss", subCategory: "ELSS", plan: "Direct", option: "Growth", nav: 319.61, navDate: "23 Aug 2026", returns: { oneYear: 16.5, threeYear: 20.2, fiveYear: 17.4, tenYear: 14.2 }, risk: "Very High", expenseRatio: 0.59, aum: "₹8,460 Cr", minSip: 500, minInvestment: 500, exitLoad: "Three-year lock-in", benchmark: "Nifty 500 TRI", manager: "Reference manager profile", inception: "2001", summary: "Equity-linked savings reference fund with a statutory lock-in.", source: "AMC factsheet reference" },
  { slug: "motilal-oswal-nasdaq-100-direct-growth", schemeCode: "MOT008", isin: "INF247L01987", name: "Motilal Oswal Nasdaq 100 Fund", amc: "Motilal Oswal Mutual Fund", category: "international", subCategory: "International FoF", plan: "Direct", option: "Growth", nav: 42.16, navDate: "23 Aug 2026", returns: { oneYear: 22.1, threeYear: 18.7, fiveYear: 20.6, tenYear: 16.4 }, risk: "Very High", expenseRatio: 0.81, aum: "₹5,120 Cr", minSip: 500, minInvestment: 500, exitLoad: "1% within 15 days", benchmark: "NASDAQ-100 TRI", manager: "Reference manager profile", inception: "2018", summary: "International reference fund providing exposure to large technology-led global companies.", source: "AMC factsheet reference" },
];

export const fundProviders = [
  { name: "SBI Mutual Fund", type: "AMC", focus: "Equity, debt, hybrid, index and solution-oriented schemes", link: "https://www.sbimf.com/", source: "Official AMC website" },
  { name: "HDFC Mutual Fund", type: "AMC", focus: "Equity, debt, hybrid, index and thematic schemes", link: "https://www.hdfcfund.com/", source: "Official AMC website" },
  { name: "AMFI", type: "Industry body", focus: "Investor education, NAV references and scheme information", link: "https://www.amfiindia.com/", source: "Official AMFI website" },
  { name: "MF Central", type: "Service platform", focus: "Consolidated mutual-fund service and investor transactions", link: "https://www.mfcentral.com/", source: "Official platform website" },
  { name: "CAMS", type: "RTA", focus: "Registrar and investor servicing for participating AMCs", link: "https://www.camsonline.com/", source: "Official RTA website" },
  { name: "KFintech", type: "RTA", focus: "Registrar and investor servicing for participating AMCs", link: "https://mfs.kfintech.com/", source: "Official RTA website" },
];

export const fundQuestions = ["What is a mutual fund?", "What is NAV?", "Direct versus regular mutual funds?", "Growth versus IDCW option?", "How does an SIP work?", "What is XIRR?", "How are mutual funds taxed?", "What is the Riskometer?", "How to redeem mutual funds?", "What is portfolio overlap?"];
export const fundSources = [{ label: "AMFI investor education", href: "https://www.amfiindia.com/investor" }, { label: "SEBI investor education", href: "https://investor.sebi.gov.in/" }, { label: "AMFI factsheets", href: "https://www.amfiindia.com/online-center/download-factsheets" }, { label: "AMFI tax reference", href: "https://www.amfiindia.com/investor/knowledge-center-info?zoneName=TaxRegimeForMutualFunds" }];

